config/routes.rb
Causeoftheday::Application.routes.draw do

  match "/organisations/:id" => 'organisations#show', :as => :organisation

  get "payment_response/credit_card"

  get "payment_response/amazon"

  devise_for :organisation_user, :controllers => { :sessions => "organisation_user_sessions", :passwords => "organisation_user_passwords" } do
    get '/login'  => 'organisation_user_sessions#new'
  end

  match 'confirm_amazon_payment' => 'payment_response#amazon'
  match 'confirm_credit_card_payment' => 'payment_response#credit_card'
  match 'confirm_paypal_payment' => 'payment_response#paypal'
  match 'paypal_notification' => 'payment_response#paypal_notification'

  devise_for :donors

  resources :donations

  resources :search, :only => [] do
    collection do
      get :causes
      get :search_results
    end
  end

  resources :payment_response, :only => [] do
    member do
      get :credit_card
    end
  end

  resources :donors do
    resources :credit_cards
  end

  resources :accounts
  resources :addresses

  resources :causes do
    resources :cause_images
    resources :cause_updates
    member do
      get :stats
    end
  end

  ['admin', 'organisation'].each do |s|
    scope :path => s do
      resources :causes do
        resources :cause_images
        resources :cause_updates
        member do
          get :stats
        end
      end
    end
  end

    resources :causes, :path => '/causes' do
      member do
        get :stats
      end
      match 'action_not_permitted' => 'causes#action_not_permitted', :as => :action_not_permitted
      match 'remove' => 'causes#remove', :as => :remove
      match 'request_approval' => 'causes#request_approval', :as => :request_approval
      resources :cause_images
      resources :cause_updates
    end

  namespace :organisation do
    match 'dashboard' => 'dashboard#index', :as => :dashboard
    match 'terms_and_conditions' => 'dashboard#terms_and_conditions', :as => :terms_and_conditions
    match 'faq' => 'dashboard#faq', :as => :faq
    resources :organisation_users
  end

  namespace :admin do
    match 'dashboard' => 'dashboard#index', :as => :dashboard

    resources :organisations
    resources :admin, :only => [:index] do
      collection do
        get :logout
      end
    end
    resources :schedules do
      collection do
        post :fetch
      end
    end
    resources :donations
  end

  match 'load_cause' => 'home#load_cause', :as => :load_cause
  match 'top_influencer' => 'home#top_influencer', :as => :top_influencer
  match 'facebook_signin' => 'signin_response#facebook', :as => :facebook_signin

  match 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  match 'faq' => 'home#faq', :as => :faq
  match 'contact_us' => 'home#contact_us', :as => :contact_us
  match 'my_donations' => 'donations#my_donations', :as => :my_donations    

  match 'tagged_causes' => 'admin/causes#tagged_causes', :as => :tagged_causes

  match 'admin' => 'admin/admin#index', :as => :admin
  match '/auth/:provider/callback' => 'accounts#create'
  match '/auth/failure' => 'accounts#failure', :as => :failure

  match 'welcome' => 'accounts#welcome', :as => :welcome
  root :to => "home#index"

end

app/models/credit_card.rb
 
class CreditCard < ActiveRecord::Base
  
  has_one :address, :as => :owner, :dependent => :destroy
  has_many :donations, :as => :mode_of_payment
  has_many :responses, :through => :donations, :class_name => 'CreditCardResponse'
  belongs_to :donor
  validate :number, :security_code
  
  validates_presence_of :donor_id

  validates :expiration_month,:expiration_year,:presence => true
  attr_encrypted :number, :key => ::ENCRYPTED_KEY_FOR_CREDIT_CARD
  attr_encrypted :security_code, :key => ::ENCRYPTED_KEY_FOR_SECURITY_CODE

  before_validation(:on => :create) do
    self.number = number.gsub(/[^0-9]/, "") if attribute_present?("number")
  end

  validate do |credit_card|
    if credit_card.new_record?
      credit_card.errors[:base] << "Number is required" if credit_card.encrypted_number.blank?
      credit_card.errors[:base] << "Security Code is required" if credit_card.encrypted_security_code.blank?
    elsif !(!credit_card.new_record? && credit_card.number.blank? && credit_card.security_code.blank?)
      credit_card.errors[:base] << "Security Code must be 3 .. 4 characters" if (credit_card.security_code.length < 3 || credit_card.security_code.length > 4)
      credit_card.errors[:base] << "Number must be 16 .. 17 characters" if (credit_card.number.length < 16 || credit_card.number.length > 17)
    end
  end
  
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_filter :authenticate_donor!, :except => [:destroy]
  def index
    @credit_cards = current_donor.credit_cards
  end
  
  def show
    @credit_card = CreditCard.find(params[:id])
  end
  
  def new
    @credit_card = CreditCard.new
  end
  
  def create
    @credit_card = CreditCard.new(params[:credit_card])
    @credit_card.donor_id = current_donor.id
    @credit_card.ip_address = request.remote_ip
    if @credit_card.save
      redirect_to new_address_path(:type_id => @credit_card.id , :type => @credit_card.class), :layout => 'application'
    else
      render :action => 'new'
    end
  end

  def edit
    @credit_card = CreditCard.find(params[:id])
  end
  
  def update
    @credit_card = CreditCard.find(params[:id])
    @credit_card.expiration_month = params[:date][:month]
    if @credit_card.update_attributes(params[:credit_card])
      flash[:notice] = "Successfully updated credit card."
      redirect_to donor_path(current_donor.id)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @credit_card = CreditCard.find(params[:id])
    @credit_card.destroy
    flash[:notice] = "Successfully destroyed credit card."
    redirect_to donor_path(current_donor.id)
  end

  
  
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
  def splitcard(number)
    if number != nil
    number.sub(/^([0-9]+)([0-9]{4})$/) { '*' * $1.length + $2 }
    end
  end
end

    

app/views/credit_cards/_credit_card.html.haml
- title "Credit Card"

%p
  %strong Card Type:
  = credit_card.card_type
%p
  %strong Card Expiration Month:
  = credit_card.expiration_month
%p
  %strong Card No:
  = splitcard(credit_card.number)

%p{:style => "margin-top: 10px;"}
  = link_to image_tag("edit.png"), edit_donor_credit_card_path(:donor_id => current_donor.id , :id => credit_card.id)
  = link_to image_tag("delete.png"), donor_credit_card_path(:donor_id => current_donor.id , :id => credit_card.id), :confirm => 'Are you sure?', :method => :delete
  

app/views/credit_cards/_form.html.haml
#rightCell
  #uinqueStyle
    %h1 Pay Online
    = f.error_messages
    %ul
      %li
        = f.hidden_field :donor_id
        = f.label :card_type
        = f.select :card_type, SiteConfig.card_type.collect {|key, type| [type, type]}, {}, :onchange => ''
      %li
        = f.label :number
        = f.text_field :number, :value => splitcard(@credit_card.number)

        - if params[:action] == 'new'
          %li
            = f.label :security_code
            = f.text_field :security_code
      %li
        = f.label :expiration_month
        = select_month(Date.today, :use_month_names => %w(Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec))
      %li
        - start_year = Time.now.year
        - end_year = 10.years.since.year
        - year = []
        - for i in start_year..end_year
          -year << i
        = f.label :expiration_year
        = f.select :expiration_year, year.collect {|value| [value, value]}, {}, :onchange => ''
      %li.signUp
        = f.submit

app/views/credit_cards/edit.html.haml
- title "Edit Credit Card"
= form_for(@credit_card, :url => donor_credit_card_path, :html => {:method => :put}) do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/credit_cards/index.html.haml
- title "Credit Cards"
%br
%h1== Credit Card details :
%br
%table{:class =>  "cardInfo"}
  %tr
    %th Card Type
    %th Card No
    %th Exp Month
    %th Exp Year
  - for credit_card in @credit_cards
    %tr
      %td= credit_card.card_type
      %td= splitcard(credit_card.number)
      %td= credit_card.expiration_month
      %td= credit_card.expiration_year
      %td= link_to "Pay Now", credit_card_payment_response_path(credit_card.id)
%br 
= link_to "Add Credit Card details", new_donor_credit_card_path(current_donor.id)

app/views/credit_cards/new.html.haml
- title "New Credit Card"
= form_for(@credit_card, :url => donor_credit_cards_path) do |f|
  = render :partial => 'form', :locals => {:f => f}
%p= link_to "Back to List", donor_credit_cards_path

app/views/credit_cards/show.html.haml
- title "Credit Card"

%p
  %strong Card Type
  = @credit_card.card_type
%p
  %strong Card expiration_month
  = @credit_card.expiration_month
%p
  %strong Card No
  = @credit_card.number
%p
  = link_to "Edit", edit_credit_card_path(@credit_card)
  |
  \#{link_to "Destroy", @credit_card, :confirm => 'Are you sure?', :method => :delete} |
  \#{link_to "View All", credit_cards_path}