config/routes.rb
Causeoftheday::Application.routes.draw do

  match "/organisations/:id" => 'organisations#show', :as => :organisation

  get "payment_response/credit_card"

  get "payment_response/amazon"

  devise_for :organisation_user, :controllers => { :sessions => "organisation_user_sessions", :passwords => "organisation_user_passwords" } do
    get '/login'  => 'organisation_user_sessions#new'
  end

  match 'confirm_amazon_payment' => 'payment_response#amazon'
  match 'confirm_credit_card_payment' => 'payment_response#credit_card'
  match 'confirm_paypal_payment' => 'payment_response#paypal'
  match 'paypal_notification' => 'payment_response#paypal_notification'

  devise_for :donors

  resources :donations

  resources :search, :only => [] do
    collection do
      get :causes
      get :search_results
    end
  end

  resources :payment_response, :only => [] do
    member do
      get :credit_card
    end
  end

  resources :donors do
    resources :credit_cards
  end

  resources :accounts
  resources :addresses

  resources :causes do
    resources :cause_images
    resources :cause_updates
    member do
      get :stats
    end
  end

  ['admin', 'organisation'].each do |s|
    scope :path => s do
      resources :causes do
        resources :cause_images
        resources :cause_updates
        member do
          get :stats
        end
      end
    end
  end

    resources :causes, :path => '/causes' do
      member do
        get :stats
      end
      match 'action_not_permitted' => 'causes#action_not_permitted', :as => :action_not_permitted
      match 'remove' => 'causes#remove', :as => :remove
      match 'request_approval' => 'causes#request_approval', :as => :request_approval
      resources :cause_images
      resources :cause_updates
    end

  namespace :organisation do
    match 'dashboard' => 'dashboard#index', :as => :dashboard
    match 'terms_and_conditions' => 'dashboard#terms_and_conditions', :as => :terms_and_conditions
    match 'faq' => 'dashboard#faq', :as => :faq
    resources :organisation_users
  end

  namespace :admin do
    match 'dashboard' => 'dashboard#index', :as => :dashboard

    resources :organisations
    resources :admin, :only => [:index] do
      collection do
        get :logout
      end
    end
    resources :schedules do
      collection do
        post :fetch
      end
    end
    resources :donations
  end

  match 'load_cause' => 'home#load_cause', :as => :load_cause
  match 'top_influencer' => 'home#top_influencer', :as => :top_influencer
  match 'facebook_signin' => 'signin_response#facebook', :as => :facebook_signin

  match 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  match 'faq' => 'home#faq', :as => :faq
  match 'contact_us' => 'home#contact_us', :as => :contact_us
  match 'my_donations' => 'donations#my_donations', :as => :my_donations    

  match 'tagged_causes' => 'admin/causes#tagged_causes', :as => :tagged_causes

  match 'admin' => 'admin/admin#index', :as => :admin
  match '/auth/:provider/callback' => 'accounts#create'
  match '/auth/failure' => 'accounts#failure', :as => :failure

  match 'welcome' => 'accounts#welcome', :as => :welcome
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :load_uuid#, :fetch_friends, :fetch_profile_image

  def index
    if current_organisation_user
      redirect_to organisation_dashboard_path
    else
      @cause = Cause.todays_cause(params[:offset_minutes].to_i)
      render :template => '/home/index'
    end
  end

  def load_cause
    @cause = Cause.todays_cause(params[:offset_minutes].to_i)
    session[:cause_id] = @cause.id if @cause
    render :partial => '/home/cause', :locals => {:cause => @cause}
  end

  def top_influencer
    @top_influencer = DonorConnection.top_influencer
    if @top_influencer
      session[:top_influencer] = @top_influencer
      render :partial => '/home/top_influencer'
    else
      render :nothing => true
    end
  end

  def how_it_works

  end

  def faq

  end

  def contact_us

  end

  private

  def load_uuid
    if params[:uuid]
      session[:uuid] = params[:uuid]
    end
  end

  def fetch_friends
    if current_donor && current_donor.twitter_user?
      session[:total_friends] = TwitterService.fetch_friends current_donor
    end
  end

  def fetch_profile_image
    if session[:top_influencer] && session[:top_influencer].twitter_user?
      session[:profile_picture] = TwitterService.profile_image session[:top_influencer]
    elsif session[:top_influencer] && session[:top_influencer].facebook_user?
      session[:profile_picture] = FacebookAccount.profile_image session[:top_influencer]
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_call_to_action.html.haml
%section.top-middle-blackbox-info
  %section.content
    %h1.heading
      Start by
      %br/
      Donating 1$
    %p
      = cause.donation_amount_collected
      people have given
    %h2
      $
      = cause.donation_amount_collected
      raised
    %section.progressbar
      %section.progress{:style => "width:#{cause.completed_amount_fraction*227}px; max-width:227px;" }
    - if current_donor
      %p= render :partial => '/home/payment_options'
    - else
      %section.donate_button
        = link_to '#', :id => 'jttrigger-0' do
          %img.domroll{:class => "/images/donate_over.png", :height => "62", :src => "/images/donor/donate_out.png", :width => "175"}/

    #jttip-0.jttip{:style => "display:none;"}
      .jttipcontent
        %ul
          %li Donate through
          %li
            %a{:href => "/auth/facebook"}
              %img{:alt => "", :height => "30", :src => "images/donor/ico_facebook.gif", :width => "30"}/
          %li
            %a{:href => "/auth/twitter"}
              %img{:alt => "", :height => "30", :src => "images/donor/ico_twitter.gif", :width => "29"}/

      =#link_to 'Login with twitter', '/auth/twitter'
      =#link_to 'Login with facebook', 'javascript:void(0)', :onclick => 'loadFacebook();'

app/views/home/_cause.html.haml
#fb-root
= javascript_include_tag 'justthetip'

- if cause
  %section.top-middle
    %section.top-middle-box
      %section.top-middle-blackbox
        %section.top-middle-blackbox-content
          %section.top-middle-blackbox-content-left
            = image_tag cause.images.first ? cause.images.first.image.url(:large) : '/images/default.jpg', :alt => cause.name, :height => "180", :src => "/images/donor/img.jpg", :title => cause.name, :width => "250"
          %section.top-middle-blackbox-content-right
            %div
              %h1
                = cause.name
              %p
                = cause.description.truncate(300)
              %p.contentlink
                = link_to "Learn More", cause_path(cause)
          .clearfloat
          %p.bottomlink
            = link_to cause.organisation.name, cause.organisation.website || '#'
      = render :partial => '/home/call_to_action', :locals => {:cause => cause}
  %section.bottom
- else
  No Cause scheduled for today. :(

  %img{:alt => "", :height => "1", :src => "/images/donor/blank.gif", :width => "1"}/

app/views/home/_payment_options.html.haml
- if current_donor
  -if !current_donor.donated?(@cause)
    Donate with -
    %ul.inline
      %li{:style => 'float:left'}= render :partial => '/payment_response/amazon_donate_button',:locals => {:cause_of_the_day => @cause}
      %li= render :partial => '/payment_response/paypal_button',:locals => {:cause_of_the_day => @cause}
  - else
    Thank you for your donation for this cause. You might want to checkout
    = link_to '97changes maintenance cause.', permanent_cause_path

app/views/home/_top_influencer.html.haml
-if session[:top_influencer] && session[:profile_picture]
  %p
    Top Influencer for today's cause
  %span
    %img{ :src => "#{session[:profile_picture]}", :title => "#{session[:top_influencer].full_name}"}

app/views/home/contact_us.html.haml
#contactUs
  %h1 We would love to hear you.
  #donors
    %h2= "Donors"
    %p
      If your have any questions about your donations please email us at &mdash;
      %a{:href => 'mailto:donations@97changes.com'}
        donations@97changes.com

  #ngo
    %h2= "Non profit organizations"
    %p
      If you are a non profit organization and would like to participate with our program, please email us at &mdash;
      %a{:href => 'mailto:participate@97changes.com'}
        participate@97changes.com

  #general
    %h2= "General inquiries"
    %p
      For all other general questions or inquiries please email us at &mdash; general@97changes.com
      %a{:href => 'mailto:general@97changes.com'}
        general@97changes.com

app/views/home/faq.html.haml
#faq
  %h1 Frequenty asked questions.
  %h2
    Q. Why the name - 97Changes?
  %div
    Numerology says 9 stands for "Humanity" and 7 stands for "Spirituality". 97Changes is about bringing in humanitarian and spirityal changes to the world.
  %h2
    Q. Why am I not allowed to make a donation for more than 1 dollar?
  %div
    We believe that the world has enough good people like yourself who want to contribute towards making things better for others. It only takes spreading the awareness of the cause to solve it.
  %h2
    Q. What if I still want to help out more?
  %div
    Certainly you can do so by spreading the word out as much as possible to people who can afford donating a 1 dollar bill today. If your humanitarian hunger is still not satiated, kindly donate towards running this application here.
  %h2
    Q.Why do I have to give my facebook or twitter ID to donate?
  %div
    The mission of 97 Changes is to make the world a better place to live by spreading the awareness. We want to shout out your commitment to humanity to your friends and make them aware of the cause.
  %h2
    Q. Will 97 Changes charge me any fees?
  %div
    No 97 Changes does not charge you anything, however a small piece of your donation goes towards the payment processing as indicated below.
    %ul
      %li
        Amazon: 3 cents
      %li
        Paypal: 7 cents
  %h2
    Q. How do I know if the donation was used the right way?
  %div
    Each cause on 97 changes is associated to some non profit organization. The details of that affiliation is listed on the cause page and you can always feel free to check with that organization to understand how was the money used.
  %h2
    Q. Up to what extent does 97 Changes verify the NGO.
  %div
    We will do our best to verify the organization and the cause associated to it. However, we do not take any legal gurantees of ensuring the same.
  %h2
    Q. Is 97 Changes registered as a non profit organization?
  %div
    No. 97 Changes is an Idyllic Software initiative towards doing social good.Idyllic Software is comitted to donate every penny collected to the associated non profit organization.
  %h2
    Q. Can I get a refund on my donation?
  %div.last
    97 changes does not have a refund policy. However, if you strongly feel so, write to us at refund@97changes.com and we will do the best we can. We wont be able to refund the processing fees though.

app/views/home/how_it_works.html.haml
#howItWorks
  %h1 How it works.
  .donors
    =image_tag 'donors.png'   
    =image_tag 'ngo.png'
    



  

app/views/home/index.html.haml
%section.top-middle-container{:id => 'todaysCause'}
  =# render :partial => 'cause', :locals => {:cause => @cause}

%section.howworks How it works
/ Bottom-box starts
%section.bottom-box
  %section.bottom-box-container
    %section.first
      %section.num 1
      %section.num-info
        %h2 Know today's change
        %p We will identify one cause every day and put it up over here. Learn about the cause.
    .devider
      %img{:alt => "", :height => "89", :src => "/images/donor/vr.gif", :width => "1"}/
    %section.second
      %section.num 2
      %section.num-info
        %h2 Commit to the cause
        %p Donate 1$ to  the cause and show your commitment .
    .devider
      %img{:alt => "", :height => "89", :src => "/images/donor/vr.gif", :width => "1"}/
    %section.third
      %section.num 3
      %section.num-info
        %h2 Broadcast
        %p We will broadcast your donation on your facebook or twitter account and shout out your social awareness to your friends.


:javascript
  $(document).ready(function() {
    loadCauseUrl = 'load_cause?offset_minutes=' + detectTimeZone();
    loadInfluencerUrl = 'top_influencer';
    $.get(loadCauseUrl,function(data){
      $('#todaysCause').html(data);
    });
    $.get(loadInfluencerUrl,function(data){
      $('#todaysInfluencer').html(data);
    });
  });