config/routes.rb
Causeoftheday::Application.routes.draw do

  match "/organisations/:id" => 'organisations#show', :as => :organisation

  get "payment_response/credit_card"

  get "payment_response/amazon"

  devise_for :organisation_user, :controllers => { :sessions => "organisation_user_sessions", :passwords => "organisation_user_passwords" } do
    get '/login'  => 'organisation_user_sessions#new'
  end

  match 'confirm_amazon_payment' => 'payment_response#amazon'
  match 'confirm_credit_card_payment' => 'payment_response#credit_card'
  match 'confirm_paypal_payment' => 'payment_response#paypal'
  match 'paypal_notification' => 'payment_response#paypal_notification'

  devise_for :donors

  resources :donations

  resources :search, :only => [] do
    collection do
      get :causes
      get :search_results
    end
  end

  resources :payment_response, :only => [] do
    member do
      get :credit_card
    end
  end

  resources :donors do
    resources :credit_cards
  end

  resources :accounts
  resources :addresses

  resources :causes do
    resources :cause_images
    resources :cause_updates
    member do
      get :stats
    end
  end

  ['admin', 'organisation'].each do |s|
    scope :path => s do
      resources :causes do
        resources :cause_images
        resources :cause_updates
        member do
          get :stats
        end
      end
    end
  end

    resources :causes, :path => '/causes' do
      member do
        get :stats
      end
      match 'action_not_permitted' => 'causes#action_not_permitted', :as => :action_not_permitted
      match 'remove' => 'causes#remove', :as => :remove
      match 'request_approval' => 'causes#request_approval', :as => :request_approval
      resources :cause_images
      resources :cause_updates
    end

  namespace :organisation do
    match 'dashboard' => 'dashboard#index', :as => :dashboard
    match 'terms_and_conditions' => 'dashboard#terms_and_conditions', :as => :terms_and_conditions
    match 'faq' => 'dashboard#faq', :as => :faq
    resources :organisation_users
  end

  namespace :admin do
    match 'dashboard' => 'dashboard#index', :as => :dashboard

    resources :organisations
    resources :admin, :only => [:index] do
      collection do
        get :logout
      end
    end
    resources :schedules do
      collection do
        post :fetch
      end
    end
    resources :donations
  end

  match 'load_cause' => 'home#load_cause', :as => :load_cause
  match 'top_influencer' => 'home#top_influencer', :as => :top_influencer
  match 'facebook_signin' => 'signin_response#facebook', :as => :facebook_signin

  match 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  match 'faq' => 'home#faq', :as => :faq
  match 'contact_us' => 'home#contact_us', :as => :contact_us
  match 'my_donations' => 'donations#my_donations', :as => :my_donations    

  match 'tagged_causes' => 'admin/causes#tagged_causes', :as => :tagged_causes

  match 'admin' => 'admin/admin#index', :as => :admin
  match '/auth/:provider/callback' => 'accounts#create'
  match '/auth/failure' => 'accounts#failure', :as => :failure

  match 'welcome' => 'accounts#welcome', :as => :welcome
  root :to => "home#index"

end

app/models/donation.rb
class Donation < ActiveRecord::Base

  belongs_to :cause
  belongs_to :donor
  belongs_to :mode_of_payment, :polymorphic => true
  belongs_to :mode_of_payment_response, :polymorphic => true

  validates_associated :cause
  validates :amount, :mode_of_payment, :mode_of_payment_response, :presence => true
  validates_numericality_of :amount

  after_create :set_location, :broadcast

  scope :donated_via, lambda { |mode_of_payment| where(:mode_of_payment_type => mode_of_payment)}

  class << self

    def build_from_response(type, user, params)
       response_klass = "#{type.to_s.camelcase}Response".constantize
       donation_attributes = response_klass.build_donation_attributes(user, params)
       Donation.new donation_attributes
    end

  end

  def amount=(value)
    super(value.scan(/\d+/).first)
  end

  private

  def set_location
    location = IpLocation.for(ip)
    self.country = location.country
    self.city = location.city
    self.save!
  end

  def broadcast
    mode_of_payment.donor.broadcast(self)
  end

end

app/controllers/admin/donations_controller.rb
class Admin::DonationsController < Admin::BaseController

  def index

  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  before_filter :find_donation, :only => [:show]

  def index
    @donations = eval("current_donor.#{params[:mode_of_payment]}.paginate(:page => params[:page], :per_page => 10)")
    influencer = Donor.find_by_uuid(session[:uuid])
    if !session[:uuid].blank? && influencer != current_donor
      DonorConnection.create!(:donor => current_donor, :cause => Donation.last.cause, :influencer => influencer)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @donations }
    end
  end
  
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @donation }
    end
  end

  def my_donations
    @donations = current_donor.donations
  end

  private

  def find_donation
    @donation = Donation.find(params[:id])
  end
  
end

app/helpers/admin/donations_helper.rb
module Admin::DonationsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for @donation do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :schedule_id %><br />
    <%= f.text_field :schedule_id %>
  </p>
  <p>
    <%= f.label :donor_id %><br />
    <%= f.text_field :donor_id %>
  </p>
  <p>
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :ip_address %><br />
    <%= f.text_field :ip_address %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/donations/edit.html.erb
<% title "Edit Donation" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @donation %> |
  <%= link_to "View All", donations_path %>
</p>

app/views/donations/index.html.haml
-if @donations
  = will_paginate(@donations)
  Donations you made so far:
  = render :partial => "payment_response/donation", :collection => @donations, :as => :donation

  = will_paginate(@donations)

app/views/donations/my_donations.html.erb
<% @donations.each do |d| %>
  <%= d.created_at %>
<% end %>

app/views/donations/new.html.erb
<% title "New Donation" %>

<%= render 'form' %>

<p><%= link_to "Back to List", donations_path %></p>

app/views/donations/show.html.erb
<% title "Donation" %>

<p>
  <strong>Schedule:</strong>
  <%= @donation.schedule_id %>
</p>
<p>
  <strong>Donor:</strong>
  <%= @donation.donor_id %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>
<p>
  <strong>Ip Address:</strong>
  <%= @donation.ip_address %>
</p>

<p>
  <%= link_to "Edit", edit_donation_path(@donation) %> |
  <%= link_to "Destroy", @donation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", donations_path %>
</p>