config/routes.rb
Causeoftheday::Application.routes.draw do

  match "/organisations/:id" => 'organisations#show', :as => :organisation

  get "payment_response/credit_card"

  get "payment_response/amazon"

  devise_for :organisation_user, :controllers => { :sessions => "organisation_user_sessions", :passwords => "organisation_user_passwords" } do
    get '/login'  => 'organisation_user_sessions#new'
  end

  match 'confirm_amazon_payment' => 'payment_response#amazon'
  match 'confirm_credit_card_payment' => 'payment_response#credit_card'
  match 'confirm_paypal_payment' => 'payment_response#paypal'
  match 'paypal_notification' => 'payment_response#paypal_notification'

  devise_for :donors

  resources :donations

  resources :search, :only => [] do
    collection do
      get :causes
      get :search_results
    end
  end

  resources :payment_response, :only => [] do
    member do
      get :credit_card
    end
  end

  resources :donors do
    resources :credit_cards
  end

  resources :accounts
  resources :addresses

  resources :causes do
    resources :cause_images
    resources :cause_updates
    member do
      get :stats
    end
  end

  ['admin', 'organisation'].each do |s|
    scope :path => s do
      resources :causes do
        resources :cause_images
        resources :cause_updates
        member do
          get :stats
        end
      end
    end
  end

    resources :causes, :path => '/causes' do
      member do
        get :stats
      end
      match 'action_not_permitted' => 'causes#action_not_permitted', :as => :action_not_permitted
      match 'remove' => 'causes#remove', :as => :remove
      match 'request_approval' => 'causes#request_approval', :as => :request_approval
      resources :cause_images
      resources :cause_updates
    end

  namespace :organisation do
    match 'dashboard' => 'dashboard#index', :as => :dashboard
    match 'terms_and_conditions' => 'dashboard#terms_and_conditions', :as => :terms_and_conditions
    match 'faq' => 'dashboard#faq', :as => :faq
    resources :organisation_users
  end

  namespace :admin do
    match 'dashboard' => 'dashboard#index', :as => :dashboard

    resources :organisations
    resources :admin, :only => [:index] do
      collection do
        get :logout
      end
    end
    resources :schedules do
      collection do
        post :fetch
      end
    end
    resources :donations
  end

  match 'load_cause' => 'home#load_cause', :as => :load_cause
  match 'top_influencer' => 'home#top_influencer', :as => :top_influencer
  match 'facebook_signin' => 'signin_response#facebook', :as => :facebook_signin

  match 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  match 'faq' => 'home#faq', :as => :faq
  match 'contact_us' => 'home#contact_us', :as => :contact_us
  match 'my_donations' => 'donations#my_donations', :as => :my_donations    

  match 'tagged_causes' => 'admin/causes#tagged_causes', :as => :tagged_causes

  match 'admin' => 'admin/admin#index', :as => :admin
  match '/auth/:provider/callback' => 'accounts#create'
  match '/auth/failure' => 'accounts#failure', :as => :failure

  match 'welcome' => 'accounts#welcome', :as => :welcome
  root :to => "home#index"

end

app/controllers/organisation_user_passwords_controller.rb
class OrganisationUserPasswordsController < Devise::PasswordsController
  layout 'organisation'

  def create
    unless params[:organisation_user][:email].present?
      flash[:error] = 'Please type your email id.'
      render :action => 'new'
    else
      if OrganisationUser.find_by_email(params[:organisation_user][:email]).present?
        super
      else
        flash[:error] = 'Invalid email id.'
        render :action => 'new'
      end
    end
  end
end

app/views/organisation_user_passwords/edit.html.haml
%h2 Change your password
= form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :put }) do |f|
  = devise_error_messages!
  = f.hidden_field :reset_password_token
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %p= f.submit "Change my password"
= render :partial => "/organisation_user_sessions/shared/links"

app/views/organisation_user_passwords/new.html.haml
%h2 Forgot your password?
= form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post }) do |f|
  #errorExplanation
    %h2
      Error :
    %ul
      %li  
        = flash[:error]
  %p
    = f.label :email
    %br/
    = f.text_field :email
  %p= f.submit "Send me reset password instructions"
= link_to 'Sign In', new_organisation_user_session_path